version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.2

    steps:
        - checkout
        - run:
            name: Build
            branches:
              only:
                - master
            command: mvn -B -DskipTests clean package

        - run:
            name: Test
            command: mvn -B test
            branches:
              only:
                - master


workflows:
    version: 2
    build-and-test:
        jobs:
        - build-and-test

        - uses: actions/checkout@master

        - uses: codecov/codecov-action@v3
          with:
            token:
              ${{ secrets.CODECOV_TOKEN }}