version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.2

    steps:
        - checkout
        - run:
            name: Build
            branches:
              only:
                - master
            command: mvn -B -DskipTests clean package

        - run:
            name: Test
            command: mvn -B test
            branches:
              only:
                - master
                -
        - run:
            name: Upload coverage data to Codecov
            command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
        - run:
            name: Code Coverage
            command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov

workflows:
  verification: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.

    jobs:
      - build-and-test:
        filters:
          branches:
            only:
              - master