version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.2

    steps:
        - checkout
        - run:
            name: Build
            branches:
              only:
                - master
            command: mvn -B -DskipTests clean package

        - run:
            name: Test
            command: mvn -B test
            branches:
              only:
                - master


        - store_artifacts:
            path: target/site/jacoco/jacoco.xml
            destination: /tmp/artifacts
        - store_artifacts:
            path: target/checkstyle-result.xml
            destination: /tmp/artifacts
        - store_artifacts:
            path: target/site/checkstyle-result.svg
            destination: /tmp/artifacts

        - run:
            name: Upload coverage data to Codecov
            command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
        - run:
            name: Code Coverage
            command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov
        - run:
            name: javadoc
            command: mvn javadoc:javadoc

        - add_ssh_keys:
            fingerprints:
              - "17:df:47:32:36:f5:5b:7b:28:db:80:72:28:17:3f:32"
        - run:
            name: deploy
            command: |
              git config --global user.name "Adel-Moumen"
              git config --global user.email "adelmoumen.pro@gmail.com"
              git clone --branch=gh-pages --depth=1 git@github.com:Adel-Moumen/ceri-m1-techniques-de-test.git gh-pages
              rm -rf gh-pages/*
              cp -R target/site/apidocs/* gh-pages/
              cd gh-pages
              git add .
              git commit -m "Javadoc Updated"
              git push origin gh-pages

workflows:
  verification: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.

    jobs:
      - build-and-test:
        filters:
          branches:
            only:
              - master